name: Android CI

on:
  push:
    branches: 
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.0.0
      with:
        java-version: '13.0.1'
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
